// proxy/src/attest/lockfile-yarn.test.ts
//
// CAUTION: own SQLite file via SQLITE_PATH, set before the dynamic import
// (same trick as lockfile.test.ts).
import { createHash, randomUUID } from 'node:crypto'
import { readFileSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { beforeEach, describe, expect, test, vi } from 'vitest'

process.env.SQLITE_PATH = path.join(os.tmpdir(), `aupm-lockfile-yarn-test-${randomUUID()}.db`)

const { default: db } = await import('../db.js')
const { setStatus } = await import('../status.js')
const lockfileModule = await import('./lockfile.js')
const {
  analyzeLockfile,
  analyzeYarnClassicLockfile,
  detectLockfileFormat,
  LOCKFILE_MAX_ENTRIES,
  LOCKFILE_MAX_YAML_BYTES,
} = lockfileModule

const encoder = new TextEncoder()
const HEADER = '# yarn lockfile v1\n'

beforeEach(() => {
  db.exec('DELETE FROM audit_status')
})

function npmEntry(version: string, integrity: string) {
  return {
    version,
    resolved: `https://registry.npmjs.org/pkg/-/pkg-${version}.tgz`,
    integrity,
  }
}

describe('detectLockfileFormat', () => {
  const detect = (type: string | undefined, text: string) =>
    detectLockfileFormat(type, encoder.encode(text))

  test.each([
    ['LF', `# THIS IS AUTOGENERATED\n${HEADER}\nms@1:\n  version "1"\n`],
    ['CRLF', '# a\r\n# yarn lockfile v1\r\n\r\nms@1:\r\n  version "1"\r\n'],
    ['a BOM', `\uFEFF${HEADER}`],
    ['no line ending', HEADER.trimEnd()],
  ])('text/plain with the header (%s) selects yarn classic', (_label, text) => {
    expect(detect('text/plain', text)).toEqual({ ok: true, format: 'yarn-classic' })
    expect(detect('text/plain; charset=utf-8', text)).toEqual({ ok: true, format: 'yarn-classic' })
  })

  test.each([
    ['a header outside the comment block', 'ms@1:\n  version "1"\n# yarn lockfile v1\n'],
    ['a header with leading space', ' # yarn lockfile v1\n'],
    ['a header with trailing text', '# yarn lockfile v1 x\n'],
    ['a header in a JSON string', '{"a": "# yarn lockfile v1"}'],
    ['a second BOM', '\uFEFF\uFEFF# yarn lockfile v1\n'],
    ['whitespace before the header', '  \n# yarn lockfile v1\n'],
  ])('%s keeps the JSON path', (_label, text) => {
    expect(detect('text/plain', text)).toEqual({ ok: true, format: 'npm' })
  })

  test('a text/plain JSON body keeps the JSON path', () => {
    expect(detect('text/plain', '{"lockfileVersion":3,"packages":{}}')).toEqual({
      ok: true,
      format: 'npm',
    })
  })

  test('the header does not select classic for another content type', () => {
    expect(detect('application/json', HEADER)).toEqual({ ok: true, format: 'npm' })
    expect(detect(undefined, HEADER)).toEqual({ ok: true, format: 'npm' })
    expect(detect('text/plainx', HEADER)).toEqual({ ok: true, format: 'npm' })
  })

  test('YAML types still select pnpm', () => {
    expect(detect('application/yaml', HEADER)).toEqual({ ok: true, format: 'pnpm' })
  })

  test('a berry body is refused and the message names the accepted formats', () => {
    const result = detect('text/plain', '__metadata:\n  version: 8\n')
    expect(result).toEqual({
      ok: false,
      message: expect.stringMatching(/package-lock\.json.*pnpm-lock\.yaml.*'9\.0'.*yarn\.lock v1/s),
    })
  })

  test('the classic header with a berry marker is refused as conflicting', () => {
    const result = detect('text/plain', `${HEADER}\n__metadata:\n  version: 8\n`)
    expect(result).toEqual({ ok: false, message: expect.stringContaining('conflicting') })
  })

  test('an indented __metadata: line is not a berry marker', () => {
    expect(detect('text/plain', `${HEADER}x@1:\n  __metadata: 1\n`)).toEqual({
      ok: true,
      format: 'yarn-classic',
    })
  })
})

describe('analyzeYarnClassicLockfile', () => {
  const fixture = readFileSync(
    path.join(import.meta.dirname, 'fixtures', 'yarn-v1.lock'),
  ) as Uint8Array
  const REG = 'https://registry.npmjs.org/ms/-/ms-1.0.0.tgz'

  function seedReviewed() {
    setStatus('ms', '2.1.3', 'COMMUNITY_REVIEWED', null, null, 'sha512-ms')
    setStatus('lodash', '4.17.21', 'COMMUNITY_REVIEWED', null, null, 'sha512-lodash')
    setStatus('tampered', '1.0.0', 'COMMUNITY_REVIEWED', null, null, 'sha512-good')
  }

  function lockWith(lines: string[]): Uint8Array {
    return encoder.encode(`${HEADER}\nms@2.1.3:\n  version "2.1.3"\n${lines.join('\n')}\n`)
  }

  function tierOfMs(result: Awaited<ReturnType<typeof analyzeYarnClassicLockfile>>): string {
    if (!result.ok) throw new Error(`must parse: ${result.message}`)
    return result.analysis.packages[0]?.tier ?? 'ABSENT'
  }

  test('matches the equivalent package-lock summary and reviewed refs', async () => {
    seedReviewed()
    const yarn = await analyzeYarnClassicLockfile(fixture)
    const npm = analyzeLockfile(
      encoder.encode(
        JSON.stringify({
          lockfileVersion: 3,
          packages: {
            '': {},
            'node_modules/@babel/core': npmEntry('1.0.0', 'sha512-babelcore'),
            'node_modules/gitdep': { version: '1.0.0', resolved: 'https://codeload.example/x.tgz' },
            'node_modules/left-pad': npmEntry('1.0.0', 'sha512-leftpad'),
            'node_modules/lodash': npmEntry('4.17.21', 'sha512-lodash'),
            'node_modules/ms': npmEntry('2.1.3', 'sha512-ms'),
            'node_modules/react': npmEntry('1.0.0', 'sha512-react'),
            'node_modules/react-dom': npmEntry('1.0.0', 'sha512-reactdom'),
            'node_modules/tampered': npmEntry('1.0.0', 'sha512-bad'),
          },
        }),
      ),
    )
    if (!yarn.ok || !npm.ok) throw new Error('both lockfiles must parse')
    expect(yarn.analysis.summary).toEqual({
      total: 8,
      reviewed: 2,
      unreviewed: 4,
      unresolvable: 1,
      integrityMismatch: 1,
    })
    expect(yarn.analysis.summary).toEqual(npm.analysis.summary)
    expect(yarn.analysis.reviewedPackageRefs).toEqual(npm.analysis.reviewedPackageRefs)
    expect(yarn.analysis.format).toBe('yarn-classic')
    const tiers = Object.fromEntries(yarn.analysis.packages.map((p) => [p.name, p.tier]))
    expect(tiers).toEqual({
      ms: 'COMMUNITY_REVIEWED',
      lodash: 'COMMUNITY_REVIEWED',
      tampered: 'INTEGRITY_MISMATCH',
      gitdep: 'UNRESOLVABLE',
    })
  })

  test('a scoped reviewed package in a grouped block is one reviewed entry', async () => {
    setStatus('@babel/core', '1.0.0', 'COMMUNITY_REVIEWED', null, null, 'sha512-babelcore')
    const result = await analyzeYarnClassicLockfile(fixture)
    if (!result.ok) throw new Error('must parse')
    expect(result.analysis.reviewedPackageRefs).toEqual([
      { pkg: '@babel/core', version: '1.0.0', auditor: null },
    ])
    expect(result.analysis.summary.total).toBe(8)
  })

  test('a BOM and CRLF do not change the result', async () => {
    seedReviewed()
    const text = Buffer.from(fixture).toString('utf8')
    const variant = encoder.encode(`\uFEFF${text.replace(/\n/g, '\r\n')}`)
    const plain = await analyzeYarnClassicLockfile(fixture)
    const changed = await analyzeYarnClassicLockfile(variant)
    if (!plain.ok || !changed.ok) throw new Error('must parse')
    expect(changed.analysis.summary).toEqual(plain.analysis.summary)
    expect(changed.analysis.packages).toEqual(plain.analysis.packages)
  })

  test('the digest covers the exact body bytes, BOM included', async () => {
    const bytes = encoder.encode(`\uFEFF${Buffer.from(fixture).toString('utf8')}`)
    const result = await analyzeYarnClassicLockfile(bytes)
    if (!result.ok) throw new Error('must parse')
    expect(result.analysis.sha256).toBe(createHash('sha256').update(bytes).digest('hex'))
  })

  test.each([
    ['a missing integrity', [`  resolved "${REG}"`]],
    ['a malformed integrity', [`  resolved "${REG}"`, '  integrity sha512-!!']],
    ['a sha1-only integrity', [`  resolved "${REG}"`, '  integrity sha1-ms']],
    ['a mismatching sha512', [`  resolved "${REG}"`, '  integrity sha512-other']],
  ])('%s on a reviewed entry is INTEGRITY_MISMATCH, never reviewed', async (_label, lines) => {
    setStatus('ms', '2.1.3', 'COMMUNITY_REVIEWED', null, null, 'sha512-ms')
    const result = await analyzeYarnClassicLockfile(lockWith(lines))
    expect(tierOfMs(result)).toBe('INTEGRITY_MISMATCH')
    if (result.ok) expect(result.analysis.summary.reviewed).toBe(0)
  })

  test('the server never replaces a missing digest with the stored review digest', async () => {
    setStatus('ms', '2.1.3', 'COMMUNITY_REVIEWED', null, null, 'sha512-ms')
    const result = await analyzeYarnClassicLockfile(lockWith([`  resolved "${REG}"`]))
    if (!result.ok) throw new Error('must parse')
    expect(result.analysis.packages[0]).toMatchObject({ integrity: null, integrityMatch: false })
  })

  test.each([
    [
      'the npmjs host with a sha1 fragment',
      'https://registry.npmjs.org/ms/-/ms-1.0.0.tgz#abc',
      true,
    ],
    ['the yarnpkg host', 'https://registry.yarnpkg.com/ms/-/ms-1.0.0.tgz', true],
    ['an upper-case host', 'https://REGISTRY.NPMJS.ORG/ms/-/ms-1.0.0.tgz', true],
    ['a git source', 'git+https://github.com/x/ms.git#abc', false],
    ['a file: source', 'file:../ms', false],
    ['a link: source', 'link:../ms', false],
    ['another host', 'https://registry.example.com/ms/-/ms-1.0.0.tgz', false],
    ['a host suffix lookalike', 'https://registry.npmjs.org.evil.com/ms/-/ms-1.0.0.tgz', false],
    ['a host prefix lookalike', 'https://evilregistry.npmjs.org/ms/-/ms-1.0.0.tgz', false],
    ['userinfo', 'https://user:pw@registry.npmjs.org/ms/-/ms-1.0.0.tgz', false],
    [
      'userinfo that hides the host',
      'https://registry.npmjs.org@evil.com/ms/-/ms-1.0.0.tgz',
      false,
    ],
    ['a backslash host trick', 'https://evil.com\\\\@registry.npmjs.org/ms/-/ms-1.0.0.tgz', false],
    ['an explicit port', 'https://registry.npmjs.org:8443/ms/-/ms-1.0.0.tgz', false],
    ['the default port written out', 'https://registry.npmjs.org:443/ms/-/ms-1.0.0.tgz', false],
    ['plain http', 'http://registry.npmjs.org/ms/-/ms-1.0.0.tgz', false],
    ['a trailing-dot host', 'https://registry.npmjs.org./ms/-/ms-1.0.0.tgz', false],
    ['a tab inside the host', 'https://registry.npm\\tjs.org/ms/-/ms-1.0.0.tgz', false],
    ['a path that is not a tarball', 'https://registry.npmjs.org/ms', false],
    ['text that is not a URL', 'ms-1.0.0.tgz', false],
  ])('resolved from %s: registry is %s', async (_label, resolved, registry) => {
    const result = await analyzeYarnClassicLockfile(
      lockWith([`  resolved "${resolved}"`, '  integrity sha512-ms']),
    )
    if (!result.ok) throw new Error(`must parse: ${result.message}`)
    expect(result.analysis.summary.unresolvable).toBe(registry ? 0 : 1)
    if (!registry) expect(result.analysis.packages[0]?.tier).toBe('UNRESOLVABLE')
  })

  test('a missing resolved field is UNRESOLVABLE, even for a reviewed package', async () => {
    setStatus('ms', '2.1.3', 'COMMUNITY_REVIEWED', null, null, 'sha512-ms')
    const result = await analyzeYarnClassicLockfile(lockWith(['  integrity sha512-ms']))
    expect(tierOfMs(result)).toBe('UNRESOLVABLE')
  })

  test('rejects a body over the byte cap with 413, before any parse starts', async () => {
    const parse = vi.fn()
    const result = await analyzeYarnClassicLockfile(
      new Uint8Array(LOCKFILE_MAX_YAML_BYTES + 1),
      undefined,
      parse,
    )
    expect(result).toMatchObject({ ok: false, status: 413 })
    expect(parse).not.toHaveBeenCalled()
  })

  test('rejects more than 10,000 entries', async () => {
    const blocks = [HEADER]
    for (let i = 0; i < LOCKFILE_MAX_ENTRIES + 1; i++) {
      blocks.push(`pkg${i}@1.0.0:\n  version "1.0.0"\n`)
    }
    const result = await analyzeYarnClassicLockfile(encoder.encode(blocks.join('\n')))
    expect(result).toEqual({ ok: false, message: expect.stringContaining('entry limit') })
  })

  test('a malformed lockfile is a 400 that names the line, never a JSON fallback', async () => {
    const result = await analyzeYarnClassicLockfile(
      encoder.encode(`${HEADER}\nms@1:\n  integrity sha512-x\n`),
    )
    expect(result).toEqual({ ok: false, message: expect.stringContaining('line 3') })
  })

  test.each([
    ['too_complex', 422],
    ['busy', 503],
  ] as const)('a %s parse outcome maps to status %i', async (kind, status) => {
    const result = await analyzeYarnClassicLockfile(fixture, undefined, async () => ({ kind }))
    expect(result).toMatchObject({ ok: false, status })
  })

  test('a busy outcome carries Retry-After seconds', async () => {
    const result = await analyzeYarnClassicLockfile(fixture, undefined, async () => ({
      kind: 'busy',
    }))
    expect(result).toMatchObject({ retryAfterSeconds: 3 })
  })
})
