// mcp/src/lockfile-entries.test.ts
import { describe, expect, it } from 'vitest'
import {
  countEntriesForFile,
  countLockfileEntries,
  countPnpmLockfileEntries,
  countYarnLockfileEntries,
  isPnpmLockfilePath,
  isYarnLockfilePath,
  LockfileParseError,
  YARN_BERRY_MESSAGE,
} from './lockfile-entries.js'

describe('countLockfileEntries', () => {
  it('counts the packages map keys, excluding the root ""', () => {
    const lockfile = JSON.stringify({
      lockfileVersion: 3,
      packages: {
        '': { name: 'root-pkg', version: '1.0.0' },
        'node_modules/ms': { version: '2.1.3' },
        'node_modules/lodash': { version: '4.17.21' },
      },
    })

    expect(countLockfileEntries(lockfile)).toBe(2)
  })

  it('counts entries from raw bytes the same way as from a string', () => {
    const lockfile = JSON.stringify({
      lockfileVersion: 2,
      packages: { '': {}, 'node_modules/ms': { version: '2.1.3' } },
    })

    expect(countLockfileEntries(Buffer.from(lockfile, 'utf8'))).toBe(1)
  })

  it('returns 0 for a lockfile with only the root entry', () => {
    const lockfile = JSON.stringify({ lockfileVersion: 3, packages: { '': {} } })
    expect(countLockfileEntries(lockfile)).toBe(0)
  })

  it('throws LockfileParseError for invalid JSON', () => {
    expect(() => countLockfileEntries('not json')).toThrow(LockfileParseError)
  })

  it('throws LockfileParseError when there is no packages map', () => {
    expect(() => countLockfileEntries(JSON.stringify({ lockfileVersion: 3 }))).toThrow(
      LockfileParseError,
    )
  })

  it('throws LockfileParseError when packages is not an object', () => {
    expect(() =>
      countLockfileEntries(JSON.stringify({ lockfileVersion: 3, packages: [] })),
    ).toThrow(LockfileParseError)
  })
})

const PNPM_LOCKFILE = `lockfileVersion: '9.0'

importers:
  .:
    dependencies:
      ms:
        specifier: 2.1.3
        version: 2.1.3

packages:

  '@babel/core@7.25.2':
    resolution: {integrity: sha512-babelcore}

  ms@2.1.3:
    resolution: {integrity: sha512-ms}

  react-dom@18.3.1:
    resolution: {integrity: sha512-reactdom}

snapshots:

  ms@2.1.3: {}

  react-dom@18.3.1(react@18.3.1): {}
`

describe('countPnpmLockfileEntries', () => {
  it('counts the keys of the packages map, not snapshots or importers', () => {
    expect(countPnpmLockfileEntries(PNPM_LOCKFILE)).toBe(3)
  })

  it('counts from raw bytes the same way as from a string', () => {
    expect(countPnpmLockfileEntries(Buffer.from(PNPM_LOCKFILE, 'utf8'))).toBe(3)
  })

  it('counts 0 when the project has no packages key', () => {
    expect(countPnpmLockfileEntries("lockfileVersion: '9.0'\n")).toBe(0)
  })

  it('rejects a lockfileVersion other than 9.0', () => {
    expect(() => countPnpmLockfileEntries("lockfileVersion: '6.0'\npackages: {}\n")).toThrow(
      /'9\.0'/,
    )
  })

  it('rejects a duplicate key in packages', () => {
    const body = "lockfileVersion: '9.0'\npackages:\n  ms@2.1.3: {}\n  ms@2.1.3: {}\n"
    expect(() => countPnpmLockfileEntries(body)).toThrow(LockfileParseError)
  })

  it('rejects a duplicate key in the root', () => {
    const body = "lockfileVersion: '9.0'\nlockfileVersion: '9.0'\n"
    expect(() => countPnpmLockfileEntries(body)).toThrow(LockfileParseError)
  })

  it('rejects invalid YAML', () => {
    expect(() => countPnpmLockfileEntries('a: [unclosed')).toThrow(LockfileParseError)
  })

  it('rejects a packages value that is not a mapping', () => {
    expect(() => countPnpmLockfileEntries("lockfileVersion: '9.0'\npackages: [a]\n")).toThrow(
      LockfileParseError,
    )
  })
})

describe('countEntriesForFile', () => {
  it('chooses the pnpm parser by file name', () => {
    expect(isPnpmLockfilePath('/work/app/pnpm-lock.yaml')).toBe(true)
    expect(isPnpmLockfilePath('/work/app/package-lock.json')).toBe(false)
    expect(countEntriesForFile('/work/app/pnpm-lock.yaml', PNPM_LOCKFILE)).toBe(3)
  })

  it('keeps the JSON parser for any other file name', () => {
    const json = JSON.stringify({ lockfileVersion: 3, packages: { '': {}, 'node_modules/ms': {} } })
    expect(countEntriesForFile('/work/app/package-lock.json', json)).toBe(1)
  })
})

const YARN_LOCKFILE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/core@^7.0.0", "@babel/core@^7.25.2":
  version "7.25.2"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.25.2.tgz#abc"
  integrity sha512-aaa
  dependencies:
    ms "^2.1.3"

ms@^2.1.3:
  version "2.1.3"
  resolved "https://registry.yarnpkg.com/ms/-/ms-2.1.3.tgz#def"
  integrity sha512-bbb
`

describe('countYarnLockfileEntries', () => {
  it('counts one entry per block; grouped selectors are one entry', () => {
    expect(countYarnLockfileEntries(YARN_LOCKFILE)).toBe(2)
  })

  it('accepts CRLF line endings, a BOM and bytes', () => {
    const crlf = `\uFEFF${YARN_LOCKFILE.replaceAll('\n', '\r\n')}`
    expect(countYarnLockfileEntries(Buffer.from(crlf, 'utf8'))).toBe(2)
  })

  it('counts 0 for a header-only lockfile', () => {
    expect(countYarnLockfileEntries('# yarn lockfile v1\n\n')).toBe(0)
  })

  it('refuses a berry lockfile with the berry message', () => {
    const berry =
      '# This file is generated by running "yarn install"\n\n__metadata:\n  version: 8\n'
    expect(() => countYarnLockfileEntries(berry)).toThrow(YARN_BERRY_MESSAGE)
  })

  it('refuses a body without the classic header, or with it only after content', () => {
    expect(() => countYarnLockfileEntries('ms@^2:\n  version "2.1.3"\n')).toThrow(
      LockfileParseError,
    )
    expect(() =>
      countYarnLockfileEntries('ms@^2:\n  version "2.1.3"\n# yarn lockfile v1\n'),
    ).toThrow(LockfileParseError)
    expect(() => countYarnLockfileEntries('# yarn lockfile v1 \n')).toThrow(LockfileParseError)
  })

  it('chooses the yarn parser by file name', () => {
    expect(isYarnLockfilePath('/work/app/yarn.lock')).toBe(true)
    expect(isYarnLockfilePath('/work/app/package-lock.json')).toBe(false)
    expect(countEntriesForFile('/work/app/yarn.lock', YARN_LOCKFILE)).toBe(2)
  })
})
